CKEDITOR.plugins.setLang( 'keybind', 'en', {
  keybindButton: 'Keybind: Insert a keyname defined by the user',
  unkeybindButton: 'Remove a Keybind',

  title: 'Insert a keyname defined by player',
  keySelect: 'Key name',


  // Nom des touches, définit dans les traductions de Minecraft (fichier lang)
  /*
    Pour ajouter une nouvelle touche:
      - Ajouter la traduction ici
      - Ajouter la touche dans la dropdownlist (fichier dialog/keybind.js:50)
  */
  forward: 'Walk Forwards',
  back: 'Walk Backwards',
  left: 'Strafe Left',
  right: 'Strafe Right',
  jump: 'Jump',
  sneak: 'Sneak',
  sprint: 'Sprint',
  inventory: 'Open/Close Inventory',
  attack: 'Attack/Destroy',
  use: 'Use Item/Place Block',
  pickItem: 'Pick Block',
  drop: 'Drop Selected Item',
  swapHands: 'Swap Item In Hands',
  hotbar_1: 'Hotbar Slot 1',
  hotbar_2: 'Hotbar Slot 2',
  hotbar_3: 'Hotbar Slot 3',
  hotbar_4: 'Hotbar Slot 4',
  hotbar_5: 'Hotbar Slot 5',
  hotbar_6: 'Hotbar Slot 6',
  hotbar_7: 'Hotbar Slot 7',
  hotbar_8: 'Hotbar Slot 8',
  hotbar_9: 'Hotbar Slot 9',
  saveToolbarActivator: 'Save Toolbar',
  loadToolbarActivator: 'Load Toolbar',
  playerlist: 'List Players',
  chat: 'Open Chat',
  command: 'Open Command',
  spectatorOutlines: 'Highlight Players (Spectators)',
  screenshot: 'Take Screenshot',
  smoothCamera: 'Toggle Cinematic Camera',
  fullscreen: 'Toggle Fullscreen',
  togglePerspective: 'Toggle Perspective',

  key_forward: 'W',
  key_back: 'S',
  key_left: 'A',
  key_right: 'D',
  key_jump: 'SPACE',
  key_sneak: 'LSHIFT',
  key_sprint: 'LCONTROL',
  key_inventory: 'E',
  key_attack: 'Left Click',
  key_use: 'Right Click',
  key_pickItem: 'Middle Click',
  key_drop: 'Q',
  key_swapHands: 'F',
  key_hotbar_1: '1',
  key_hotbar_2: '2',
  key_hotbar_3: '3',
  key_hotbar_4: '4',
  key_hotbar_5: '5',
  key_hotbar_6: '6',
  key_hotbar_7: '7',
  key_hotbar_8: '8',
  key_hotbar_9: '9',
  key_saveToolbarActivator: 'C',
  key_loadToolbarActivator: 'X',
  key_playerlist: 'TAB',
  key_chat: 'T',
  key_command: '/',
  key_spectatorOutlines: 'NONE',
  key_screenshot: 'F2',
  key_smoothCamera: 'NONE',
  key_fullscreen: 'F11',
  key_togglePerspective: 'F5',

} );
